// <auto-generated />
using System;
using Dragonwright.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dragonwright.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260130231803_AddInitialCharacterEntities")]
    partial class AddInitialCharacterEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackgroundFeat", b =>
                {
                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GrantedFeatsId")
                        .HasColumnType("uuid");

                    b.HasKey("BackgroundId", "GrantedFeatsId");

                    b.HasIndex("GrantedFeatsId");

                    b.ToTable("BackgroundFeat");
                });

            modelBuilder.Entity("BackgroundItem", b =>
                {
                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecificWeaponProficienciesId")
                        .HasColumnType("uuid");

                    b.HasKey("BackgroundId", "SpecificWeaponProficienciesId");

                    b.HasIndex("SpecificWeaponProficienciesId");

                    b.ToTable("BackgroundItem");
                });

            modelBuilder.Entity("BackgroundSpell", b =>
                {
                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellListId")
                        .HasColumnType("uuid");

                    b.HasKey("BackgroundId", "SpellListId");

                    b.HasIndex("SpellListId");

                    b.ToTable("BackgroundSpell");
                });

            modelBuilder.Entity("CharacterItem", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecificArmorProficienciesId")
                        .HasColumnType("uuid");

                    b.HasKey("CharacterId", "SpecificArmorProficienciesId");

                    b.HasIndex("SpecificArmorProficienciesId");

                    b.ToTable("CharacterItem");
                });

            modelBuilder.Entity("CharacterItem1", b =>
                {
                    b.Property<Guid>("Character1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecificWeaponProficienciesId")
                        .HasColumnType("uuid");

                    b.HasKey("Character1Id", "SpecificWeaponProficienciesId");

                    b.HasIndex("SpecificWeaponProficienciesId");

                    b.ToTable("CharacterItem1");
                });

            modelBuilder.Entity("CharacterItem2", b =>
                {
                    b.Property<Guid>("Character2Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecificToolProficienciesId")
                        .HasColumnType("uuid");

                    b.HasKey("Character2Id", "SpecificToolProficienciesId");

                    b.HasIndex("SpecificToolProficienciesId");

                    b.ToTable("CharacterItem2");
                });

            modelBuilder.Entity("ClassItem", b =>
                {
                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpecificWeaponProficienciesId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassId", "SpecificWeaponProficienciesId");

                    b.HasIndex("SpecificWeaponProficienciesId");

                    b.ToTable("ClassItem");
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.Property<Guid>("ClassesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellListId")
                        .HasColumnType("uuid");

                    b.HasKey("ClassesId", "SpellListId");

                    b.HasIndex("SpellListId");

                    b.ToTable("ClassSpell");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Background", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityScoreIncreases")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArmorProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LanguageCount")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageRestrictions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SkillProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Backgrounds");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityScoreGenerationMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AdvancementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Alignment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Allies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AllowMulticlassing")
                        .HasColumnType("boolean");

                    b.Property<string>("Appearance")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ArmorClassBonus")
                        .HasColumnType("integer");

                    b.Property<string>("ArmorProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ArrowQuiver")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("Backstory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("BlindsightNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("BlindsightRange")
                        .HasColumnType("integer");

                    b.Property<int>("BoltQuiver")
                        .HasColumnType("integer");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CheckMulticlassingPrerequisites")
                        .HasColumnType("boolean");

                    b.Property<string>("ConditionDefenses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Copper")
                        .HasColumnType("integer");

                    b.Property<bool>("CountMoneyWeight")
                        .HasColumnType("boolean");

                    b.Property<int>("CurrentHitDie")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentHitPoints")
                        .HasColumnType("integer");

                    b.Property<bool>("CustomizeOrigin")
                        .HasColumnType("boolean");

                    b.Property<string>("DamageDefenses")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DarkvisionNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DarkvisionRange")
                        .HasColumnType("integer");

                    b.Property<int>("Electrum")
                        .HasColumnType("integer");

                    b.Property<string>("Enemies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("ExceedLevelCap")
                        .HasColumnType("boolean");

                    b.Property<int>("ExhaustionLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Eyes")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Faith")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FlyingSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<int>("Gold")
                        .HasColumnType("integer");

                    b.Property<string>("Hair")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("HeightInInches")
                        .HasColumnType("integer");

                    b.Property<int>("HitPointBonus")
                        .HasColumnType("integer");

                    b.Property<string>("HitPointType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InitiativeBonus")
                        .HasColumnType("integer");

                    b.Property<int>("InspirationPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lifestyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MaxHitDie")
                        .HasColumnType("integer");

                    b.Property<int>("MovementSpeed")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OptionalClassFeatures")
                        .HasColumnType("boolean");

                    b.Property<string>("Organizations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OverriddenMaximumHitPoints")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveInsightBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PassiveInvestigationBonus")
                        .HasColumnType("integer");

                    b.Property<int>("PassivePerceptionBonus")
                        .HasColumnType("integer");

                    b.Property<string>("PersonalityTraits")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RawMaximumHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("SavingThrowAdvantages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavingThrowDisadvantages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Silver")
                        .HasColumnType("integer");

                    b.Property<int>("Size")
                        .HasColumnType("integer");

                    b.Property<string>("Skin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Sources")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SwimmingSpeed")
                        .HasColumnType("integer");

                    b.Property<int>("TemporaryHitPoints")
                        .HasColumnType("integer");

                    b.Property<string>("ToolProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TremorsenseNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TremorsenseRange")
                        .HasColumnType("integer");

                    b.Property<string>("TruesightNote")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TruesightRange")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("WeaponProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeightInPounds")
                        .HasColumnType("integer");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterAbility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ability")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverrideSavingThrowProficiency")
                        .HasColumnType("text");

                    b.Property<string>("RawSavingThrowProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RawScore")
                        .HasColumnType("integer");

                    b.Property<int>("SavingThrowBonus")
                        .HasColumnType("integer");

                    b.Property<int>("ScoreBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterAbilities");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterBackground", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("CharacterBackgrounds");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("ClassFeatureUsages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SubclassId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ClassId");

                    b.HasIndex("SubclassId");

                    b.ToTable("CharacterClasses");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterFeat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FeatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("FeatId");

                    b.ToTable("CharacterFeats");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Attuned")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Equipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("ItemId");

                    b.ToTable("CharacterItems");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterRace", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<string>("RaceTraitUsages")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.HasIndex("RaceId");

                    b.ToTable("CharacterRaces");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdvantageState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Bonus")
                        .HasColumnType("integer");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<string>("OverrideProficiency")
                        .HasColumnType("text");

                    b.Property<string>("RawProficiency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Skill")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.ToTable("CharacterSkills");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId");

                    b.HasIndex("SpellId");

                    b.ToTable("CharacterSpells");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Characteristics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.ToTable("Characteristics");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArmorProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("BaseHitPointsAtFirstLevel")
                        .HasColumnType("integer");

                    b.Property<int>("FixHitPointsPerLevelAfterFirst")
                        .HasColumnType("integer");

                    b.Property<int>("HitDie")
                        .HasColumnType("integer");

                    b.Property<int?>("HitPointsModifierAbilityScore")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryAbilityScores")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SavingThrowProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SkillProficienciesCount")
                        .HasColumnType("integer");

                    b.Property<string>("SkillProficienciesOptions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponProficiencies")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.ClassFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsOptional")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.ToTable("ClassFeatures");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Creature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Feat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Feats");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Item", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ArmorClassBonus")
                        .HasColumnType("integer");

                    b.Property<string>("ArmorClassBonusAbility")
                        .HasColumnType("text");

                    b.Property<int>("AttackBonus")
                        .HasColumnType("integer");

                    b.Property<int?>("BaseArmorClass")
                        .HasColumnType("integer");

                    b.Property<int>("DamageBonus")
                        .HasColumnType("integer");

                    b.Property<string>("DamageBonusAbility")
                        .HasColumnType("text");

                    b.Property<int>("DamageDice")
                        .HasColumnType("integer");

                    b.Property<int>("DamageDieCount")
                        .HasColumnType("integer");

                    b.Property<string>("DamageTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DoffingTimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<int>("DonningTimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<bool>("GivesDisadvantageOnStealth")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBackpack")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMagical")
                        .HasColumnType("boolean");

                    b.Property<string>("Mastery")
                        .HasColumnType("text");

                    b.Property<int>("MaximumArmorClassBonusFromAbility")
                        .HasColumnType("integer");

                    b.Property<int>("MaximumRangeInFeet")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RangeInFeet")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequiredAbilityScore")
                        .HasColumnType("text");

                    b.Property<int>("RequiredAbilityScoreValue")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("boolean");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ToolType")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ValueInCopper")
                        .HasColumnType("integer");

                    b.Property<string>("WeaponProperties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponType")
                        .HasColumnType("text");

                    b.Property<int>("WeightInOunces")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Modifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityScore")
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("DiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiceValue")
                        .HasColumnType("integer");

                    b.Property<string>("Duration")
                        .HasColumnType("text");

                    b.Property<int>("FixedValue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<string>("Subtype")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaceTraitId");

                    b.ToTable("Modifiers");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Race", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Races");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTrait", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CharactersLevelWhereOptionsArePresented")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("FeatureType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HideInBuilder")
                        .HasColumnType("boolean");

                    b.Property<bool>("HideInCharacterSheet")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("RaceId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredCharacterLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TraitToReplaceId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceId");

                    b.HasIndex("TraitToReplaceId");

                    b.ToTable("RaceTraits");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityScore")
                        .HasColumnType("text");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ActivationTime")
                        .HasColumnType("text");

                    b.Property<int?>("AreaOfEffect")
                        .HasColumnType("integer");

                    b.Property<int>("AreaSize")
                        .HasColumnType("integer");

                    b.Property<string>("AttackType")
                        .HasColumnType("text");

                    b.Property<string>("DamageType")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DiceCount")
                        .HasColumnType("integer");

                    b.Property<int>("DiceValue")
                        .HasColumnType("integer");

                    b.Property<bool>("DisplayAsAttack")
                        .HasColumnType("boolean");

                    b.Property<bool>("EffectByMartialArts")
                        .HasColumnType("boolean");

                    b.Property<string>("EffectOnMiss")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EffectOnSaveFailure")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("EffectOnSaveSuccess")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("FixedSaveDC")
                        .HasColumnType("integer");

                    b.Property<int>("FixedValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsNaturalWeapon")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsProficient")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUnarmedWeapon")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaximumRange")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Range")
                        .HasColumnType("integer");

                    b.Property<int>("RequiredCharacterLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ResetType")
                        .HasColumnType("text");

                    b.Property<string>("Save")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RaceTraitId");

                    b.ToTable("RaceTraitActions");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitCreature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("ChallengeRatingLevelDivisor")
                        .HasColumnType("integer");

                    b.Property<string>("CreatureGroup")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatureSizes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CreatureType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ExistingCreatureId")
                        .HasColumnType("uuid");

                    b.Property<float?>("MaxChallengeRating")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<string>("RestrictedMovementTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ExistingCreatureId");

                    b.HasIndex("RaceTraitId");

                    b.ToTable("RaceTraitCreatures");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<int>("RequiredCharacterLevel")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequiredOptionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RaceTraitId");

                    b.HasIndex("RequiredOptionId");

                    b.ToTable("RaceTraitOptions");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitSpell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbilityScore")
                        .HasColumnType("text");

                    b.Property<string>("ActivationTimeUnit")
                        .HasColumnType("text");

                    b.Property<string>("AdditionalDescription")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<bool>("AlwaysPrepared")
                        .HasColumnType("boolean");

                    b.Property<string>("AttackTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AvailableAtCharacterLevel")
                        .HasColumnType("integer");

                    b.Property<int?>("CastAtLevel")
                        .HasColumnType("integer");

                    b.Property<string>("CastingTime")
                        .HasColumnType("text");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<bool>("ConsumesSpellSlot")
                        .HasColumnType("boolean");

                    b.Property<bool>("CountsAsKnownSpell")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInfinite")
                        .HasColumnType("boolean");

                    b.Property<int>("LevelDivisor")
                        .HasColumnType("integer");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("integer");

                    b.Property<bool>("NumberOfUsesProficiencyBonusIfProficient")
                        .HasColumnType("boolean");

                    b.Property<string>("NumberOfUsesProficiencyOperation")
                        .HasColumnType("text");

                    b.Property<int?>("NumberOfUsesStatModifierAbility")
                        .HasColumnType("integer");

                    b.Property<string>("NumberOfUsesStatModifierOperation")
                        .HasColumnType("text");

                    b.Property<bool>("OnlyRitualSpells")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Range")
                        .HasColumnType("integer");

                    b.Property<string>("ResetType")
                        .HasColumnType("text");

                    b.Property<string>("Restrictions")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("SpellId")
                        .HasColumnType("uuid");

                    b.Property<string>("SpellLevels")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SpellSchools")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("RaceTraitId");

                    b.HasIndex("SpellId");

                    b.ToTable("RaceTraitSpells");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AbsoluteExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceName")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TokenFamily")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("TokenFamily");

                    b.HasIndex("UserId", "DeviceId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Spell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int?>("AreaOfEffect")
                        .HasColumnType("integer");

                    b.Property<int>("AreaSize")
                        .HasColumnType("integer");

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CastingTimes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Concentration")
                        .HasColumnType("boolean");

                    b.Property<string>("Conditions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DamageTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Durations")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasMaterialComponent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSomaticComponent")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVocalComponent")
                        .HasColumnType("boolean");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("MaterialComponents")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Range")
                        .HasColumnType("integer");

                    b.Property<bool>("Ritual")
                        .HasColumnType("boolean");

                    b.Property<int?>("Save")
                        .HasColumnType("integer");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Spells");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChoiceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .HasColumnType("text");

                    b.Property<int?>("CurrencyAmount")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponProperties")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WeaponTypes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.ToTable("StartItems");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StartItemChoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("BackgroundId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<int>("Operator")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BackgroundId");

                    b.HasIndex("ClassId");

                    b.ToTable("StartItemChoices");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StoragePath")
                        .IsUnique();

                    b.ToTable("StoredFiles");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Subclass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("SourceCreatorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("SourceCreatorId");

                    b.ToTable("Subclasses");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AvatarId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AvatarId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RaceTraitSpell", b =>
                {
                    b.Property<Guid>("RaceTraitId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SpellListId")
                        .HasColumnType("uuid");

                    b.HasKey("RaceTraitId", "SpellListId");

                    b.HasIndex("SpellListId");

                    b.ToTable("RaceTraitSpell");
                });

            modelBuilder.Entity("BackgroundFeat", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Feat", null)
                        .WithMany()
                        .HasForeignKey("GrantedFeatsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackgroundItem", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("SpecificWeaponProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BackgroundSpell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", null)
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterItem", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("SpecificArmorProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterItem1", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("Character1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("SpecificWeaponProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CharacterItem2", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", null)
                        .WithMany()
                        .HasForeignKey("Character2Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("SpecificToolProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassItem", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", null)
                        .WithMany()
                        .HasForeignKey("SpecificWeaponProficienciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ClassSpell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Class", null)
                        .WithMany()
                        .HasForeignKey("ClassesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Background", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Character", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.StoredFile", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dragonwright.Database.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Avatar");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterAbility", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Abilities")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterBackground", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", "Background")
                        .WithMany()
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithOne("Background")
                        .HasForeignKey("Dragonwright.Database.Entities.CharacterBackground", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Background");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterClass", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Classes")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Subclass", "Subclass")
                        .WithMany()
                        .HasForeignKey("SubclassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Character");

                    b.Navigation("Class");

                    b.Navigation("Subclass");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterFeat", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Feats")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Feat", "Feat")
                        .WithMany()
                        .HasForeignKey("FeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Feat");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterItem", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Items")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterRace", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithOne("Race")
                        .HasForeignKey("Dragonwright.Database.Entities.CharacterRace", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Race", "Race")
                        .WithMany()
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterSkill", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Skills")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.CharacterSpell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Character", "Character")
                        .WithMany("Spells")
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Characteristics", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", null)
                        .WithMany("Characteristics")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Class", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.ClassFeature", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Class", null)
                        .WithMany("Features")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Feat", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Item", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Modifier", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", null)
                        .WithMany("Modifiers")
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Race", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTrait", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Race", null)
                        .WithMany("Traits")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", "TraitToReplace")
                        .WithMany()
                        .HasForeignKey("TraitToReplaceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TraitToReplace");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitAction", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", "RaceTrait")
                        .WithMany("Actions")
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RaceTrait");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitCreature", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Creature", "ExistingCreature")
                        .WithMany()
                        .HasForeignKey("ExistingCreatureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", "RaceTrait")
                        .WithMany("Creatures")
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExistingCreature");

                    b.Navigation("RaceTrait");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitOption", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", "RaceTrait")
                        .WithMany("Options")
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.RaceTraitOption", "RequiredOption")
                        .WithMany()
                        .HasForeignKey("RequiredOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RaceTrait");

                    b.Navigation("RequiredOption");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTraitSpell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", "RaceTrait")
                        .WithMany("Spells")
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Spell", "Spell")
                        .WithMany()
                        .HasForeignKey("SpellId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("RaceTrait");

                    b.Navigation("Spell");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RefreshToken", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Spell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StartItem", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.StartItemChoice", "Choice")
                        .WithMany("Items")
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Choice");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StartItemChoice", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Background", null)
                        .WithMany("StartingItems")
                        .HasForeignKey("BackgroundId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dragonwright.Database.Entities.Class", null)
                        .WithMany("StartingItems")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Subclass", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.Class", "Class")
                        .WithMany("Subclasses")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.User", "SourceCreator")
                        .WithMany()
                        .HasForeignKey("SourceCreatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Class");

                    b.Navigation("SourceCreator");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.User", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.StoredFile", "Avatar")
                        .WithMany()
                        .HasForeignKey("AvatarId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Avatar");
                });

            modelBuilder.Entity("RaceTraitSpell", b =>
                {
                    b.HasOne("Dragonwright.Database.Entities.RaceTrait", null)
                        .WithMany()
                        .HasForeignKey("RaceTraitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Dragonwright.Database.Entities.Spell", null)
                        .WithMany()
                        .HasForeignKey("SpellListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Background", b =>
                {
                    b.Navigation("Characteristics");

                    b.Navigation("StartingItems");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Character", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Background");

                    b.Navigation("Classes");

                    b.Navigation("Feats");

                    b.Navigation("Items");

                    b.Navigation("Race");

                    b.Navigation("Skills");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Class", b =>
                {
                    b.Navigation("Features");

                    b.Navigation("StartingItems");

                    b.Navigation("Subclasses");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.Race", b =>
                {
                    b.Navigation("Traits");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.RaceTrait", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Creatures");

                    b.Navigation("Modifiers");

                    b.Navigation("Options");

                    b.Navigation("Spells");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.StartItemChoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Dragonwright.Database.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
