using System.Text.Json.Serialization;

namespace Dragonwright.Database.Entities.Modifiers;

[JsonPolymorphic(TypeDiscriminatorPropertyName = "$type")]
[JsonDerivedType(typeof(BonusSubtype), nameof(ModifierType.Bonus))]
[JsonDerivedType(typeof(DamageSubtype), nameof(ModifierType.Damage))]
[JsonDerivedType(typeof(AdvantageSubtype), nameof(ModifierType.Advantage))]
[JsonDerivedType(typeof(DisadvantageSubtype), nameof(ModifierType.Disadvantage))]
[JsonDerivedType(typeof(ResistanceSubtype), nameof(ModifierType.Resistance))]
[JsonDerivedType(typeof(ImmunitySubtype), nameof(ModifierType.Immunity))]
[JsonDerivedType(typeof(VulnerabilitySubtype), nameof(ModifierType.Vulnerability))]
[JsonDerivedType(typeof(SenseSubtype), nameof(ModifierType.Sense))]
[JsonDerivedType(typeof(SetSubtype), nameof(ModifierType.Set))]
[JsonDerivedType(typeof(HalfProficiencySubtype), nameof(ModifierType.HalfProficiency))]
[JsonDerivedType(typeof(ProficiencySubtype), nameof(ModifierType.Proficiency))]
[JsonDerivedType(typeof(ExpertiseSubtype), nameof(ModifierType.Expertise))]
[JsonDerivedType(typeof(LanguageSubtype), nameof(ModifierType.Language))]
[JsonDerivedType(typeof(FeatSubtype), nameof(ModifierType.Feat))]
[JsonDerivedType(typeof(CarryingCapacitySubtype), nameof(ModifierType.CarryingCapacity))]
[JsonDerivedType(typeof(NaturalWeaponSubtype), nameof(ModifierType.NaturalWeapon))]
[JsonDerivedType(typeof(StealthDisadvantageSubtype), nameof(ModifierType.StealthDisadvantage))]
[JsonDerivedType(typeof(SpeedReductionSubtype), nameof(ModifierType.SpeedReduction))]
[JsonDerivedType(typeof(SpeedIncreaseSubtype), nameof(ModifierType.SpeedIncrease))]
[JsonDerivedType(typeof(MeleeWeaponAttackSubtype), nameof(ModifierType.MeleeWeaponAttack))]
[JsonDerivedType(typeof(RangedWeaponAttackSubtype), nameof(ModifierType.RangedWeaponAttack))]
[JsonDerivedType(typeof(WeaponPropertySubtype), nameof(ModifierType.WeaponProperty))]
[JsonDerivedType(typeof(HalfProficiencyRoundUpSubtype), nameof(ModifierType.HalfProficiencyRoundUp))]
[JsonDerivedType(typeof(FavoredEnemySubtype), nameof(ModifierType.FavoredEnemy))]
[JsonDerivedType(typeof(IgnoreSubtype), nameof(ModifierType.Ignore))]
[JsonDerivedType(typeof(EldritchBlastSubtype), nameof(ModifierType.EldrichBlast))]
[JsonDerivedType(typeof(ReplaceDamageTypeSubtype), nameof(ModifierType.ReplaceDamageType))]
[JsonDerivedType(typeof(TwiceProficiencySubtype), nameof(ModifierType.TwiceProficiency))]
[JsonDerivedType(typeof(MonkWeaponSubtype), nameof(ModifierType.MonkWeapon))]
[JsonDerivedType(typeof(ProtectionSubtype), nameof(ModifierType.Protection))]
[JsonDerivedType(typeof(StackingBonusSubtype), nameof(ModifierType.StackingBonus))]
[JsonDerivedType(typeof(SetBaseSubtype), nameof(ModifierType.SetBase))]
[JsonDerivedType(typeof(IgnoreWeaponPropertySubtype), nameof(ModifierType.IgnoreWeaponProperty))]
[JsonDerivedType(typeof(SizeSubtype), nameof(ModifierType.Size))]
[JsonDerivedType(typeof(WeaponMasterySubtype), nameof(ModifierType.WeaponMastery))]
[JsonDerivedType(typeof(EnableFeatureSubtype), nameof(ModifierType.EnableFeature))]
[JsonDerivedType(typeof(ReplaceWeaponAbilitySubtype), nameof(ModifierType.ReplaceWeaponAbility))]
public abstract class ModifierSubtype;