/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Dragonwright | v1
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from './http';
export interface AuthResponse {
  accessToken?: string;
  refreshToken?: string;
  accessTokenExpiration?: string;
}

export interface LoginRequest {
  username: string;
  password: string;
  deviceId: string;
  /** @nullable */
  deviceName?: string | null;
}

export interface LogoutRequest {
  refreshToken: string;
}

export interface ProblemDetails {
  /** @nullable */
  type?: string | null;
  /** @nullable */
  title?: string | null;
  /**
   * @nullable
   * @pattern ^-?(?:0|[1-9]\d*)$
   */
  status?: number | string | null;
  /** @nullable */
  detail?: string | null;
  /** @nullable */
  instance?: string | null;
}

export interface RefreshRequest {
  accessToken: string;
  refreshToken: string;
}

export interface RegisterRequest {
  /**
   * @minLength 3
   * @maxLength 32
   */
  username: string;
  /** @minLength 8 */
  password: string;
  deviceId: string;
  /** @nullable */
  deviceName?: string | null;
}

export type postAuthRegisterResponse200 = {
  data: AuthResponse
  status: 200
}

export type postAuthRegisterResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postAuthRegisterResponse409 = {
  data: ProblemDetails
  status: 409
}
    
export type postAuthRegisterResponseSuccess = (postAuthRegisterResponse200) & {
  headers: Headers;
};
export type postAuthRegisterResponseError = (postAuthRegisterResponse400 | postAuthRegisterResponse409) & {
  headers: Headers;
};

export type postAuthRegisterResponse = (postAuthRegisterResponseSuccess | postAuthRegisterResponseError)

export const getPostAuthRegisterUrl = () => {


  

  return `/auth/register`
}

export const postAuthRegister = async (registerRequest: RegisterRequest, options?: RequestInit): Promise<postAuthRegisterResponse> => {
  
  return customFetch<postAuthRegisterResponse>(getPostAuthRegisterUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      registerRequest,)
  }
);}



export type postAuthLoginResponse200 = {
  data: AuthResponse
  status: 200
}

export type postAuthLoginResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postAuthLoginResponse401 = {
  data: ProblemDetails
  status: 401
}
    
export type postAuthLoginResponseSuccess = (postAuthLoginResponse200) & {
  headers: Headers;
};
export type postAuthLoginResponseError = (postAuthLoginResponse400 | postAuthLoginResponse401) & {
  headers: Headers;
};

export type postAuthLoginResponse = (postAuthLoginResponseSuccess | postAuthLoginResponseError)

export const getPostAuthLoginUrl = () => {


  

  return `/auth/login`
}

export const postAuthLogin = async (loginRequest: LoginRequest, options?: RequestInit): Promise<postAuthLoginResponse> => {
  
  return customFetch<postAuthLoginResponse>(getPostAuthLoginUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      loginRequest,)
  }
);}



export type postAuthRefreshResponse200 = {
  data: AuthResponse
  status: 200
}

export type postAuthRefreshResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postAuthRefreshResponse401 = {
  data: ProblemDetails
  status: 401
}
    
export type postAuthRefreshResponseSuccess = (postAuthRefreshResponse200) & {
  headers: Headers;
};
export type postAuthRefreshResponseError = (postAuthRefreshResponse400 | postAuthRefreshResponse401) & {
  headers: Headers;
};

export type postAuthRefreshResponse = (postAuthRefreshResponseSuccess | postAuthRefreshResponseError)

export const getPostAuthRefreshUrl = () => {


  

  return `/auth/refresh`
}

export const postAuthRefresh = async (refreshRequest: RefreshRequest, options?: RequestInit): Promise<postAuthRefreshResponse> => {
  
  return customFetch<postAuthRefreshResponse>(getPostAuthRefreshUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      refreshRequest,)
  }
);}



export type postAuthLogoutResponse200 = {
  data: void
  status: 200
}

export type postAuthLogoutResponse400 = {
  data: ProblemDetails
  status: 400
}

export type postAuthLogoutResponse401 = {
  data: ProblemDetails
  status: 401
}
    
export type postAuthLogoutResponseSuccess = (postAuthLogoutResponse200) & {
  headers: Headers;
};
export type postAuthLogoutResponseError = (postAuthLogoutResponse400 | postAuthLogoutResponse401) & {
  headers: Headers;
};

export type postAuthLogoutResponse = (postAuthLogoutResponseSuccess | postAuthLogoutResponseError)

export const getPostAuthLogoutUrl = () => {


  

  return `/auth/logout`
}

export const postAuthLogout = async (logoutRequest: LogoutRequest, options?: RequestInit): Promise<postAuthLogoutResponse> => {
  
  return customFetch<postAuthLogoutResponse>(getPostAuthLogoutUrl(),
  {      
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(
      logoutRequest,)
  }
);}



export type postAuthLogoutAllResponse200 = {
  data: void
  status: 200
}

export type postAuthLogoutAllResponse401 = {
  data: ProblemDetails
  status: 401
}
    
export type postAuthLogoutAllResponseSuccess = (postAuthLogoutAllResponse200) & {
  headers: Headers;
};
export type postAuthLogoutAllResponseError = (postAuthLogoutAllResponse401) & {
  headers: Headers;
};

export type postAuthLogoutAllResponse = (postAuthLogoutAllResponseSuccess | postAuthLogoutAllResponseError)

export const getPostAuthLogoutAllUrl = () => {


  

  return `/auth/logout-all`
}

export const postAuthLogoutAll = async ( options?: RequestInit): Promise<postAuthLogoutAllResponse> => {
  
  return customFetch<postAuthLogoutAllResponse>(getPostAuthLogoutAllUrl(),
  {      
    ...options,
    method: 'POST'
    
    
  }
);}
