/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/characters/': RouteRecordInfo<
      '/characters/',
      '/characters',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/characters/[id]/': RouteRecordInfo<
      '/characters/[id]/',
      '/characters/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit': RouteRecordInfo<
      '/characters/[id]/edit',
      '/characters/:id/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | '/characters/[id]/edit/abilities'
      | '/characters/[id]/edit/background'
      | '/characters/[id]/edit/class'
      | '/characters/[id]/edit/configuration'
      | '/characters/[id]/edit/details'
      | '/characters/[id]/edit/race'
    >,
    '/characters/[id]/edit/abilities': RouteRecordInfo<
      '/characters/[id]/edit/abilities',
      '/characters/:id/edit/abilities',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit/background': RouteRecordInfo<
      '/characters/[id]/edit/background',
      '/characters/:id/edit/background',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit/class': RouteRecordInfo<
      '/characters/[id]/edit/class',
      '/characters/:id/edit/class',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit/configuration': RouteRecordInfo<
      '/characters/[id]/edit/configuration',
      '/characters/:id/edit/configuration',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit/details': RouteRecordInfo<
      '/characters/[id]/edit/details',
      '/characters/:id/edit/details',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/characters/[id]/edit/race': RouteRecordInfo<
      '/characters/[id]/edit/race',
      '/characters/:id/edit/race',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/': RouteRecordInfo<
      '/content/',
      '/content',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/backgrounds/': RouteRecordInfo<
      '/content/backgrounds/',
      '/content/backgrounds',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/backgrounds/[id]': RouteRecordInfo<
      '/content/backgrounds/[id]',
      '/content/backgrounds/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/backgrounds/new': RouteRecordInfo<
      '/content/backgrounds/new',
      '/content/backgrounds/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/classes/': RouteRecordInfo<
      '/content/classes/',
      '/content/classes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/classes/[id]': RouteRecordInfo<
      '/content/classes/[id]',
      '/content/classes/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/classes/new': RouteRecordInfo<
      '/content/classes/new',
      '/content/classes/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/feats/': RouteRecordInfo<
      '/content/feats/',
      '/content/feats',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/feats/[id]': RouteRecordInfo<
      '/content/feats/[id]',
      '/content/feats/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/feats/new': RouteRecordInfo<
      '/content/feats/new',
      '/content/feats/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/items/': RouteRecordInfo<
      '/content/items/',
      '/content/items',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/items/[id]': RouteRecordInfo<
      '/content/items/[id]',
      '/content/items/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/items/new': RouteRecordInfo<
      '/content/items/new',
      '/content/items/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/languages/': RouteRecordInfo<
      '/content/languages/',
      '/content/languages',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/languages/[id]': RouteRecordInfo<
      '/content/languages/[id]',
      '/content/languages/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/languages/new': RouteRecordInfo<
      '/content/languages/new',
      '/content/languages/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/races/': RouteRecordInfo<
      '/content/races/',
      '/content/races',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/races/[id]': RouteRecordInfo<
      '/content/races/[id]',
      '/content/races/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/races/new': RouteRecordInfo<
      '/content/races/new',
      '/content/races/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/spells/': RouteRecordInfo<
      '/content/spells/',
      '/content/spells',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/content/spells/[id]': RouteRecordInfo<
      '/content/spells/[id]',
      '/content/spells/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/content/spells/new': RouteRecordInfo<
      '/content/spells/new',
      '/content/spells/new',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/characters/index.vue': {
      routes:
        | '/characters/'
      views:
        | never
    }
    'src/pages/characters/[id]/index.vue': {
      routes:
        | '/characters/[id]/'
      views:
        | never
    }
    'src/pages/characters/[id]/edit.vue': {
      routes:
        | '/characters/[id]/edit'
        | '/characters/[id]/edit/abilities'
        | '/characters/[id]/edit/background'
        | '/characters/[id]/edit/class'
        | '/characters/[id]/edit/configuration'
        | '/characters/[id]/edit/details'
        | '/characters/[id]/edit/race'
      views:
        | 'default'
    }
    'src/pages/characters/[id]/edit/abilities.vue': {
      routes:
        | '/characters/[id]/edit/abilities'
      views:
        | never
    }
    'src/pages/characters/[id]/edit/background.vue': {
      routes:
        | '/characters/[id]/edit/background'
      views:
        | never
    }
    'src/pages/characters/[id]/edit/class.vue': {
      routes:
        | '/characters/[id]/edit/class'
      views:
        | never
    }
    'src/pages/characters/[id]/edit/configuration.vue': {
      routes:
        | '/characters/[id]/edit/configuration'
      views:
        | never
    }
    'src/pages/characters/[id]/edit/details.vue': {
      routes:
        | '/characters/[id]/edit/details'
      views:
        | never
    }
    'src/pages/characters/[id]/edit/race.vue': {
      routes:
        | '/characters/[id]/edit/race'
      views:
        | never
    }
    'src/pages/content/index.vue': {
      routes:
        | '/content/'
      views:
        | never
    }
    'src/pages/content/backgrounds/index.vue': {
      routes:
        | '/content/backgrounds/'
      views:
        | never
    }
    'src/pages/content/backgrounds/[id].vue': {
      routes:
        | '/content/backgrounds/[id]'
      views:
        | never
    }
    'src/pages/content/backgrounds/new.vue': {
      routes:
        | '/content/backgrounds/new'
      views:
        | never
    }
    'src/pages/content/classes/index.vue': {
      routes:
        | '/content/classes/'
      views:
        | never
    }
    'src/pages/content/classes/[id].vue': {
      routes:
        | '/content/classes/[id]'
      views:
        | never
    }
    'src/pages/content/classes/new.vue': {
      routes:
        | '/content/classes/new'
      views:
        | never
    }
    'src/pages/content/feats/index.vue': {
      routes:
        | '/content/feats/'
      views:
        | never
    }
    'src/pages/content/feats/[id].vue': {
      routes:
        | '/content/feats/[id]'
      views:
        | never
    }
    'src/pages/content/feats/new.vue': {
      routes:
        | '/content/feats/new'
      views:
        | never
    }
    'src/pages/content/items/index.vue': {
      routes:
        | '/content/items/'
      views:
        | never
    }
    'src/pages/content/items/[id].vue': {
      routes:
        | '/content/items/[id]'
      views:
        | never
    }
    'src/pages/content/items/new.vue': {
      routes:
        | '/content/items/new'
      views:
        | never
    }
    'src/pages/content/languages/index.vue': {
      routes:
        | '/content/languages/'
      views:
        | never
    }
    'src/pages/content/languages/[id].vue': {
      routes:
        | '/content/languages/[id]'
      views:
        | never
    }
    'src/pages/content/languages/new.vue': {
      routes:
        | '/content/languages/new'
      views:
        | never
    }
    'src/pages/content/races/index.vue': {
      routes:
        | '/content/races/'
      views:
        | never
    }
    'src/pages/content/races/[id].vue': {
      routes:
        | '/content/races/[id]'
      views:
        | never
    }
    'src/pages/content/races/new.vue': {
      routes:
        | '/content/races/new'
      views:
        | never
    }
    'src/pages/content/spells/index.vue': {
      routes:
        | '/content/spells/'
      views:
        | never
    }
    'src/pages/content/spells/[id].vue': {
      routes:
        | '/content/spells/[id]'
      views:
        | never
    }
    'src/pages/content/spells/new.vue': {
      routes:
        | '/content/spells/new'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
